### ISSUE TITLE
你好，CurrentUser 无法获取当前用户，没有缓存已登录用户

### ISSUE THREAD

**Issue by brandy2015** [leancloud/swift-sdk-demo#35]
你好，CurrentUser 无法获取当前用户，没有缓存已登录用户

**Comment by zapcannon87** [comment]
请升级 [Swift SDK](https://github.com/leancloud/swift-sdk) 到最新版后再试试。

**Comment by brandy2015** [comment]
已升级17.7.0

**Comment by brandy2015** [comment]
![截屏2021-03-25 上午9 50 02](https://user-images.githubusercontent.com/10484324/112406967-27d36e80-8d50-11eb-86d9-c7abb5af543e.png)

**Comment by brandy2015** [comment]
再次登陆后无法获取当前用户，同次登陆可以获取，一直用sessionToken再次登陆，可否，直接获取上次打开时候的用户

**Comment by brandy2015** [comment]
我注意到一个问题，用户名是英文可以正常在再次登陆时获取CurrentUser，但是用户名是中文则没办法获取用户

**Comment by zapcannon87** [comment]
能提供一个触发了该问题的中文用户名**样例**吗？如果确认是中文用户名导致的，我们这边应该可以复现该问题。

**Comment by brandy2015** [comment]
比如，张阿三

**Comment by zapcannon87** [comment]
我们这边测试后，发现没有什么问题，一切正常。

请问能提供具体的测试代码吗？

**Comment by brandy2015** [comment]
您是退出界面后重新进入界面再获取的用户currentUser吗，你重新进入后再获取
![截屏2021-03-27 下午1 24 10](https://user-images.githubusercontent.com/10484324/112710946-b89c7c80-8eff-11eb-8801-f5e264807dab.png)

**Comment by brandy2015** [comment]
[❤️][error][LeanCloud][2021-03-27 13:24:01.726][User.swift][#111][currentUser(application:)]: Error Domain=NSCocoaErrorDomain Code=3840 "Unescaped control character around character 1494." UserInfo={NSDebugDescription=Unescaped control character around character 1494.}
没有登陆

**Comment by zapcannon87** [comment]
我们这边针对该问题，发布了一个[新版](https://github.com/leancloud/swift-sdk/releases/tag/17.7.1)，您可以稍后更新之后再试试（如果是用 pod 集成，建议在半小时后再更新，因为 CDN 的同步有延迟）。

另外，因为该问题涉及本地缓存数据，建议更新完成后，先清理本地缓存（例如删除应用），或主动进行一次 User 登录操作（覆盖旧缓存）。

**Comment by brandy2015** [comment]
好的，非常感谢

**Comment by brandy2015** [comment]
已经收到新版本，问题解决了，非常感谢
